# Ansible playbook to setup a new OS
# Path: playbooks/os_setup.yml
---

- name: play
  hosts: all
  gather_facts: no

  tasks:
    - name: use os_setup role
      include_role:
        name: os_setup