# Ansible playbook to setup a new OS
# Path: playbooks/os_setup.yml
---

- name: play
  hosts: all
  gather_facts: True

  tasks:
    - name: Setup application
      include_role:
        name: web_server_setup