---
# tasks file for ./roles/zfs_setup/tasks/main.yml
- name: "Set facts"
  include_tasks: setting_facts.yml

- name: "Install zfs"
  include_tasks: setup_zfs.yml
  when: zfs_installed == false

- name: "Setup pool"
  include_tasks: setup_pool.yml