- name: Install epel
  dnf:
    name: epel-release

- name: Install upgrades
  dnf:
    name: '*'
    state: latest

- name: Install kernel-devel
  dnf:
    name: kernel-devel
    state: latest

- name: Install zfs-release
  shell: "dnf install https://zfsonlinux.org/epel/zfs-release-2-2$(rpm --eval \"%{dist}\").noarch.rpm -y"

- name: Import gpg key
  shell: "gpg --import --import-options show-only /etc/pki/rpm-gpg/RPM-GPG-KEY-openzfs"

- name: Install zfs
  dnf:
    name: zfs
    state: latest

- name: Reboot
  reboot:
    reboot_timeout: 600

- name: Wait for host to come back
  wait_for_connection:
    delay: 10
    timeout: 600

- name: modprobe zfs
  shell: "modprobe zfs"