---
# handlers file for application_setup
- name: Reload systemd
  shell: "systemctl daemon-reload"
  changed_when: false

- name: Reload udev
  shell: udevadm control --reload-rules ; udevadm trigger