- name: Set the user to create
  ansible.builtin.set_fact:
    user_to_setup: cashfactory
    group_to_setup: cashfactory
    homedir: /opt/cashfactory

- name: Setup cashfactory user
  ansible.builtin.include_tasks: setup_user.yml

- name: Setting service information
  ansible.builtin.set_fact:
    service:
      description: cashfactory container service
      userhome: "{{ homedir }}"
      username: cashfactory
      usergroup: cashfactory
      uid: "{{ created_user.uid }}"

- name: Get default router ipv4 address
  ansible.builtin.set_fact:
    router_ip: "{{ ansible_default_ipv4.gateway }}"

- name: Generate md5 hash for cashfactory hostname
  ansible.builtin.set_fact:
    cashfactory_hash: "{{ ansible_hostname | hash('md5') }}"

- name: Template cashfactory-compose.yml
  ansible.builtin.template:
    src: cashfactory/cashfactory-compose.yml.j2
    dest: /opt/cashfactory/docker-compose.yml
    owner: cashfactory
    group: cashfactory
    mode: 0600

- name: Template env file
  ansible.builtin.template:
    src: cashfactory/cashfactory.env.j2
    dest: /opt/cashfactory/.env
    owner: cashfactory
    group: cashfactory
    mode: 0600

- name: Template cashfactory service file
  ansible.builtin.template:
    src: generic_compose.service.j2
    dest: /etc/systemd/system/cashfactory.service
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Enable and start cashfactory service
  ansible.builtin.systemd:
    name: cashfactory
    enabled: yes
    state: restarted
    daemon_reload: yes