- name: Set the user to create
  ansible.builtin.set_fact:
    user_to_setup: gitlab
    group_to_setup: gitlab
    homedir: /opt/gitlab

- name: Setup gitlab user
  ansible.builtin.include_tasks: setup_user.yml

- name: Setting service information
  ansible.builtin.set_fact:
    service:
      description: gitlab container service
      userhome: "{{ homedir }}"
      username: gitlab
      usergroup: gitlab
      uid: "{{ created_user.uid }}"

- name: Template gitlab-compose.yml
  ansible.builtin.template:
    src: gitlab/gitlab-compose.yml.j2
    dest: /opt/gitlab/docker-compose.yml
    owner: gitlab
    group: gitlab
    mode: 0600

- name: Template env file
  ansible.builtin.template:
    src: gitlab/gitlab.env.j2
    dest: /opt/gitlab/.env
    owner: gitlab
    group: gitlab
    mode: 0600

- name: Template gitlab service file
  ansible.builtin.template:
    src: generic_compose.service.j2
    dest: /etc/systemd/system/gitlab.service
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Enable and start gitlab service
  ansible.builtin.systemd:
    name: gitlab
    enabled: yes
    state: restarted
    daemon_reload: yes
