---
# tasks file for application_setup
- name: Gather facts
  gather_facts:

- name: Install podman and podman-compose
  include_tasks: podman_install.yml

- name: Install authentik
  include_tasks: authentik.yml
  tags:
    - authentik

- name: Install home-assistant
  include_tasks: home_assistant.yml
  tags:
    - home_assistant

- name: Install nextcloud
  include_tasks: nextcloud.yml
  tags:
    - nextcloud

- name: Install monitoring
  include_tasks: monitoring.yml
  tags:
    - monitoring

- name: Install media_stack
  include_tasks: media_stack.yml
  tags:
    - media_stack