- name: Set the user to create
  set_fact:
    user_to_setup: media_stack
    homedir: /opt/media_stack

- name: Setup home assistant user
  include_tasks: setup_user.yml

- name: Setting service information
  set_fact:
    service:
      description: media_stack service
      userhome: "{{ homedir }}"
      username: media_stack
      usergroup: media_stack
      uid: "{{ created_user.uid }}"

- name: Create homedir directory
  file:
    path: "{{ homedir }}/{{ item }}"
    state: directory
    owner: media_stack
    group: media_stack
    mode: 0755
  with_items:
    - config
    - config/gluetun
    - config/bazarr
    - config/jellyfin
    - config/jellyseerr
    - config/lidarr
    - config/mylar3
    - config/prowlarr
    - config/qbittorrent
    - config/radarr
    - config/readarr
    - config/sabnzbd
    - config/sonarr
    - config/tdarr
    - config/tdarr/server
    - config/tdarr/configs
    - config/tdarr/logs
    - config/unpackerr
    - data

- name: Mount and bind /mnt/main_datastore/media to   {{ homedir }}/data
  mount:
    path: "{{ homedir }}/data"
    src: /mnt/main_datastore/media
    opts: bind
    state: mounted
    fstype: none

- name: Create subdir in /media_stack/data
  file:
    path: "{{ homedir }}/{{ item }}"
    state: directory
    owner: media_stack
    group: media_stack
    mode: 0755
  with_items:
    - data
    - data/media
    - data/media/tdarr_transcode_cache
    - data/media/movies
    - data/media/tv_shows
    - data/media/ebooks

- name: Template media_stack-compose.yml
  template:
    src: media_stack-compose.yml.j2
    dest: "{{ homedir }}/docker-compose.yml"
    owner: media_stack
    group: media_stack
    mode: 0600

- name: Template media_stack.env file
  template:
    src: media_stack.env.j2
    dest: "{{ homedir }}/.env"
    owner: media_stack
    group: media_stack
    mode: 0600

- name: Template media_stack service file
  template:
    src: generic_compose.service.j2
    dest: /etc/systemd/system/media_stack.service
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Enable media_stack service and start it
  systemd:
    name: media_stack
    enabled: yes
    state: restarted
    daemon_reload: yes
