- name: Install podman
  dnf:
    name:
      - podman
      - podman-docker
    state: latest

- name: Get latest version of docker-compose
  shell: "curl -u {{ github_auth }} -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name'"
  register: compose_version
  delegate_to: localhost
  run_once: true

- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version.stdout }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Start and enable podman.socket
  systemd:
    name: podman.socket
    state: started
    enabled: yes

